final draft of css project
pulibrary/css_project_Swarren pull request #1
Opened 2023-08-30 14:46 UTC by Seanwarren77

finished css project

2023-08-31 13:43 UTC, hackartisan commented on index.html
> +  <body>
This line should move up to line 8 -- the `body` tag should start right after the `head` tag ends

2023-08-31 13:46 UTC, hackartisan requested changes
This looks really fantastic. The html is well-structured and nicely organized (just one fix noted inline), the class names are informative, the css is clear, nice use of flexbox, everything is easy to read.

2023-09-05 13:19 UTC, Seanwarren77 commented
@hackartisan thank you I addressed the problem you flagged for me.  Please take another look?

2023-09-05 13:20 UTC, hackartisan approved these changes

2023-09-05 13:21 UTC, merged